services:
  - type: web
    runtime: node
    name: syncwatch
    repo: https://github.com/pedznuque/syncwatch.git
    branch: main
    region: singapore
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /health
    autoDeployTrigger: commit
    envVars:
      - key: NODE_ENV
        value: production
      - key: TURN_URLS
        sync: false
      - key: TURN_USERNAME
        sync: false
      - key: TURN_CREDENTIAL
        sync: false
