name: Package browser extension

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "extension/**"
      - ".github/workflows/extension.yml"

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create extension package
        run: cd extension && zip -r ../syncwatch-web-player.zip .
      - uses: actions/upload-artifact@v4
        with:
          name: SyncWatch-Web-Player
          path: syncwatch-web-player.zip
